### ISSUE TITLE
Readme/Doc update for new SDK with breaking changes

### ISSUE THREAD

**Issue by Dev-JamesR** [Ether1Project/ethofs-sdk#12]
Can we create an updated set of docs and examples making it easier to use the new sdk with breaking changes?

**Comment by Dev-JamesR** [comment]
The latest doc updates look great, I will be adding a few more items. Nice work!

**Comment by newCodeRunner** [comment]
Just pushed the changes. Let me know if there is anything else to be done? like an example folder with web pack config and setup for web and/or node?

**Comment by Dev-JamesR** [comment]
Yes, ideally an example folder with immediately/easily deployable examples of both types (node/sever side and webpack/client side)

**Comment by Legacytrx** [comment]
New documentation updated
