### ISSUE TITLE
ethofs.calculateCost(readableStreamForFile, options)

### ISSUE THREAD

**Issue by Legacytrx** [Ether1Project/ethofs-sdk#5]
The cost calculation should not require the upload of a file, but only make a simple calculation and return the cost based on a number of bytes.

**Comment by Dev-JamesR** [comment]
Integrated on https://github.com/Ether1Project/ethofs-sdk/commit/32e9cdf3134d474288bb18a72b99d6a41253092d

**Comment by Legacytrx** [comment]
Implemented
