### ISSUE TITLE
Enrich pinFileToIPFS response with blocknr when contract was instantiated

### ISSUE THREAD

**Issue by Legacytrx** [Ether1Project/ethofs-sdk#6]
Request to improve the response on successful contract establishment

Response
{
    ipfsHash: This is the IPFS multi-hash provided back for your content,
    ethoTXHash: This is transaction hash of the confirmed upload contract on the Ether-1 Network,
    uploadCost: This is the total cost in ETHO for the upload
    ethoBlockNr: This is the block when the contract has been instantiated
}

**Comment by Dev-JamesR** [comment]
Added initiationBlock and expirationBlock on https://github.com/Ether1Project/ethofs-sdk/commit/934884a2b779de34e143e7c07db6b5cbf0b8fb61

**Comment by Legacytrx** [comment]
Implemented
