### ISSUE TITLE
Inifinite length storage

### ISSUE THREAD

**Issue by Legacytrx** [Ether1Project/ethofs-sdk#8]
In order to have NFTs with permanent access to IPFS we need to have the possibility to the IPFS storage contract not to expire.

The permanent tier should be conditioned in order of size and should be allowed to be cancled.

**Comment by newCodeRunner** [comment]
@Dev-JamesR , is this one more related to backend? I don't see why we can not use the current api to have duration as long as 10 years or 100? should have enough money though :D

**Comment by Dev-JamesR** [comment]
Yeah, for this to be implemented we would need an on chain and node update to allow infinite storage. We first need to have a more in depth discussion over how this should be implemented, costs, terms, etc. More to come on this issue

**Comment by Legacytrx** [comment]
Will be implemented with new contracts in the backend
